@extends('layouts.app')

@section('title')
Task Manager
@endsection
@section('content')
 
            <div class="row">
                  <div class="col-lg-12">
                      <!--breadcrumbs start -->
                      <ul class="breadcrumb">
                          <li><a href="{{ url('dashboard') }}"><i class="fa fa-home"></i>{{ trans('dashboard_lang.panel_title') }}</a></li>
                          <li class="active">Task Manager</li>
                      </ul>
                      <!--breadcrumbs end -->
                  </div>
              </div>
              <!-- page start-->
              <div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              Task Manager
                          </header>
                          @if(Session::has('message'))   
                            <div class="white-box">
                              @if(Session::get('message') == trans('topbar_menu_lang.success'))
                              <div class="alert alert-success" data-dismiss="alert" aria-label="close">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{ Session::get('message') }}
                              </div>
                              @else
                              <div class="alert alert-warning fade in" id='gritter-notice-wrapper' data-dismiss="alert" aria-label="close">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{ Session::get('message') }}
                              </div>
                              @endif
                            </div>
                            @endif
                            @if(Session::has('data'))   
                            <div class="container">
                              <div class="alert alert-success fade in" id='gritter-notice-wrapper' data-dismiss="alert" aria-label="close">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                {{ Session::get('data') }}
                              </div>
                            </div>
                            @endif
                  <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                          <li class="active">
                              <a data-toggle="tab" href="#view"><i class="fa fa-ellipsis-v"></i> Clear View </a>
                          </li>
                          <li class="">
                              <a data-toggle="tab" href="#config"><i class="fa fa-ellipsis-v"></i> Clear Config Cache</a>
                          </li>
                          <li class="">
                              <a data-toggle="tab" href="#cache"><i class="fa fa-ellipsis-v"></i> Clear Cache </a>
                          </li>
                          <li class="">
                              <a data-toggle="tab" href="#restore"><i class="fa fa-ellipsis-v"></i> Restore System</a>
                          </li>
                          <li class="">
                              <a data-toggle="tab" href="#passport"><i class="fa fa-ellipsis-v"></i> Install Passport</a>
                          </li>
              <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="tab_1">
                <div class="tab-content">
                <div class="room-box tab-pane fade in active" style="margin:0px;" id="view">
                    <h3 class="text-primary" style="margin-left:15px">Clear View</h3>
                    <p style="margin-left:15px">This will allow you to clear the compiled views that has been generated by the system, and save disk space</p>
                    <p style="margin-left:15px"><a href="{{ url('task_manager/view') }}"><button type="submit" class="btn btn-send">Execute</button></a></p>
                </div>
                <div class="room-box tab-pane fade in" style="margin:0px" id="config">
                    <h3 class="text-primary" style="margin-left:15px">Clear Config Cache</h3>
                    <p style="margin-left:15px">Remove the configuration cache file</p>
                    <p style="margin-left:15px"><a href="{{ url('task_manager/config') }}"><button type="submit" class="btn btn-send">Execute</button></a></p>
                </div>
                <div class="room-box tab-pane fade in" style="margin:0px" id="cache">
                    <h3 class="text-primary" style="margin-left:15px">Clear Cache</h3>
                    <p style="margin-left:15px">Remove the configuration cache file</p>
                    <p style="margin-left:15px"><a href="{{ url('task_manager/cache') }}"><button type="submit" class="btn btn-send">Execute</button></a></p>
                </div>
                <div class="room-box tab-pane fade in" style="margin:0px" id="restore">
                    <h3 class="text-primary" style="margin-left:15px">Restore System</h3>
                    <p style="margin-left:15px">Restore system back to default, please make sure you backup before executing this command </p>
                    <p style="margin-left:15px"><a href="{{ url('task_manager/restore') }}"><button type="submit" class="btn btn-send">Execute</button></a></p>
                </div>
                <div class="room-box tab-pane fade in" style="margin:0px" id="passport">
                    <h3 class="text-primary" style="margin-left:15px">Install Passport</h3>
                    <p style="margin-left:15px">Helps install laravel passport with few clicks away</p>
                    <p style="margin-left:15px"><a href="{{ url('task_manager/passport') }}"><button type="submit" class="btn btn-send">Execute</button></a></p>
                </div>
              </div>
              </div>
            </div>
            <!-- /.tab-content -->
          </div>
                      </section>
                  </div>
              </div>
               

@endsection


